appearance:
  default: system
  switcher: true

plugins:
  components:
    "@evidence-dev/core-components": {}

  datasources:
    "@evidence-dev/duckdb": {}
    "@evidence-dev/source-javascript": {}
